# Generated by Django 5.2.7 on 2025-10-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
