# Generated by Django 5.2.7 on 2025-10-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_event_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("meal", "Прием пищи"),
                    ("walk", "Прогулка"),
                    ("sport", "Спорт"),
                    ("other", "Другое"),
                    ("medicine", "Лекарство"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
